### ISSUE TITLE
extsmaild can kill child processes before they've finished writing to stderr

### ISSUE THREAD

**Issue by ltratt** [ltratt/extsmail#54]
This isn't a correctness issue per se, but it means that child processes are killed possibly before they've been able to tell us why they've gone wrong.

This requires a bit of thought as both `write_to_child` needs changing so that it keeps pumping a child process even when fd/stdin are possibly dead, and then `next_with_kill` needs to be rethought, as we want to print out stderr information if there is any (and `next_with_kill` is too eager).

Problem spotted by @stephenrkell.

**Comment by oliv3** [comment]
Done in #55.
